#!/bin/sh
# Claude Code's native Amazon Bedrock backend and AWS credential chain.
PROVIDER_NAME="bedrock"
PROVIDER_DESC="Anthropic Claude through native Amazon Bedrock integration"

BASE_URL="native://amazon-bedrock"
MODEL="sonnet"
CONTEXT_TOKENS=""

MODEL_OPUS="opus"
MODEL_SONNET="sonnet"
MODEL_HAIKU="haiku"
MODEL_SUBAGENT="sonnet"

EFFORT="max"
AUTH_MODE="native"
NATIVE_BACKEND="bedrock"
EXTRA_ENV="CLAUDE_CODE_USE_BEDROCK=1"
PASSTHROUGH_ENV="AWS_PROFILE AWS_REGION AWS_DEFAULT_REGION AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY AWS_SESSION_TOKEN AWS_BEARER_TOKEN_BEDROCK ANTHROPIC_SMALL_FAST_MODEL_AWS_REGION"

PRE_START=""
POST_STOP=""
HEALTH_CHECK_URL=""
