#!/bin/sh
# Claude Code's native Vertex AI backend and Google ADC credential chain.
PROVIDER_NAME="vertex"
PROVIDER_DESC="Anthropic Claude through native Google Vertex AI integration"

BASE_URL="native://google-vertex-ai"
MODEL="sonnet"
CONTEXT_TOKENS=""

MODEL_OPUS="opus"
MODEL_SONNET="sonnet"
MODEL_HAIKU="haiku"
MODEL_SUBAGENT="sonnet"

EFFORT="max"
AUTH_MODE="native"
NATIVE_BACKEND="vertex"
EXTRA_ENV="CLAUDE_CODE_USE_VERTEX=1"
PASSTHROUGH_ENV="ANTHROPIC_VERTEX_PROJECT_ID CLOUD_ML_REGION GOOGLE_APPLICATION_CREDENTIALS GOOGLE_CLOUD_PROJECT GOOGLE_CLOUD_QUOTA_PROJECT"

PRE_START=""
POST_STOP=""
HEALTH_CHECK_URL=""
