#!/bin/sh
# Volcengine Ark Coding Plan; model IDs retain the documented dots.
PROVIDER_NAME="volcengine"
PROVIDER_DESC="Volcengine Ark Coding Plan"

BASE_URL="https://ark.cn-beijing.volces.com/api/coding"
MODEL="doubao-seed-2.0-code"
CONTEXT_TOKENS=""
MODEL_OPUS="doubao-seed-2.0-code"
MODEL_SONNET="doubao-seed-2.0-code"
MODEL_HAIKU="doubao-seed-2.0-lite"
MODEL_SUBAGENT="doubao-seed-2.0-code"
MODEL_ALIASES="doubao-seed-2.0-pro ark-code-latest"
EFFORT="high"

AUTH_MODE="surfaces"
PLAN_URL="https://ark.cn-beijing.volces.com/api/coding"
PLAN_AUTH_TYPE="bearer"
PLAN_KEY_ENV="VOLCENGINE_CODING_PLAN_KEY"
PLAN_KEYS="volcengine-coding-plan"
PLAN_MODEL="doubao-seed-2.0-code"
PLAN_MODEL_OPUS="doubao-seed-2.0-code"
PLAN_MODEL_SONNET="doubao-seed-2.0-code"
PLAN_MODEL_HAIKU="doubao-seed-2.0-lite"
PLAN_MODEL_SUBAGENT="doubao-seed-2.0-code"

ASSET_PROFILE="volcengine"
EXTRA_ENV="CLAUDE_CODE_DISABLE_NONESSENTIAL_TRAFFIC=1"
PRE_START=""
POST_STOP=""
HEALTH_CHECK_URL=""
